export enum PlayerActionType {
  CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG',
  CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST',
  CHANGE_CURRENT_SONG_INDEX = 'CHANGE_CURRENT_SONG_INDEX',
  CHANGE_SEQUENCE = 'CHANGE_SEQUENCE',
  CHANGE_PRE_SONG_INDEX = 'CHANGE_PRE_SONG_INDEX'
}